package unicorn.com.xhsr.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FLOOR".
 */
public class Floor implements java.io.Serializable {

    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private String name;
    private int orderNo;
    /** Not-null value. */
    private String buildingId;

    public Floor() {
    }

    public Floor(String objectId) {
        this.objectId = objectId;
    }

    public Floor(String objectId, String name, int orderNo, String buildingId) {
        this.objectId = objectId;
        this.name = name;
        this.orderNo = orderNo;
        this.buildingId = buildingId;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }

    /** Not-null value. */
    public String getBuildingId() {
        return buildingId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId;
    }

}
