package unicorn.com.xhsr.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import unicorn.com.xhsr.greendao.ProcessingMode;
import unicorn.com.xhsr.greendao.ProcessingTimeLimit;
import unicorn.com.xhsr.greendao.EmergencyDegree;
import unicorn.com.xhsr.greendao.EquipmentCategory;
import unicorn.com.xhsr.greendao.Equipment;
import unicorn.com.xhsr.greendao.Building;
import unicorn.com.xhsr.greendao.Floor;
import unicorn.com.xhsr.greendao.DepartmentCategory;
import unicorn.com.xhsr.greendao.Department;

import unicorn.com.xhsr.greendao.ProcessingModeDao;
import unicorn.com.xhsr.greendao.ProcessingTimeLimitDao;
import unicorn.com.xhsr.greendao.EmergencyDegreeDao;
import unicorn.com.xhsr.greendao.EquipmentCategoryDao;
import unicorn.com.xhsr.greendao.EquipmentDao;
import unicorn.com.xhsr.greendao.BuildingDao;
import unicorn.com.xhsr.greendao.FloorDao;
import unicorn.com.xhsr.greendao.DepartmentCategoryDao;
import unicorn.com.xhsr.greendao.DepartmentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig processingModeDaoConfig;
    private final DaoConfig processingTimeLimitDaoConfig;
    private final DaoConfig emergencyDegreeDaoConfig;
    private final DaoConfig equipmentCategoryDaoConfig;
    private final DaoConfig equipmentDaoConfig;
    private final DaoConfig buildingDaoConfig;
    private final DaoConfig floorDaoConfig;
    private final DaoConfig departmentCategoryDaoConfig;
    private final DaoConfig departmentDaoConfig;

    private final ProcessingModeDao processingModeDao;
    private final ProcessingTimeLimitDao processingTimeLimitDao;
    private final EmergencyDegreeDao emergencyDegreeDao;
    private final EquipmentCategoryDao equipmentCategoryDao;
    private final EquipmentDao equipmentDao;
    private final BuildingDao buildingDao;
    private final FloorDao floorDao;
    private final DepartmentCategoryDao departmentCategoryDao;
    private final DepartmentDao departmentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        processingModeDaoConfig = daoConfigMap.get(ProcessingModeDao.class).clone();
        processingModeDaoConfig.initIdentityScope(type);

        processingTimeLimitDaoConfig = daoConfigMap.get(ProcessingTimeLimitDao.class).clone();
        processingTimeLimitDaoConfig.initIdentityScope(type);

        emergencyDegreeDaoConfig = daoConfigMap.get(EmergencyDegreeDao.class).clone();
        emergencyDegreeDaoConfig.initIdentityScope(type);

        equipmentCategoryDaoConfig = daoConfigMap.get(EquipmentCategoryDao.class).clone();
        equipmentCategoryDaoConfig.initIdentityScope(type);

        equipmentDaoConfig = daoConfigMap.get(EquipmentDao.class).clone();
        equipmentDaoConfig.initIdentityScope(type);

        buildingDaoConfig = daoConfigMap.get(BuildingDao.class).clone();
        buildingDaoConfig.initIdentityScope(type);

        floorDaoConfig = daoConfigMap.get(FloorDao.class).clone();
        floorDaoConfig.initIdentityScope(type);

        departmentCategoryDaoConfig = daoConfigMap.get(DepartmentCategoryDao.class).clone();
        departmentCategoryDaoConfig.initIdentityScope(type);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        processingModeDao = new ProcessingModeDao(processingModeDaoConfig, this);
        processingTimeLimitDao = new ProcessingTimeLimitDao(processingTimeLimitDaoConfig, this);
        emergencyDegreeDao = new EmergencyDegreeDao(emergencyDegreeDaoConfig, this);
        equipmentCategoryDao = new EquipmentCategoryDao(equipmentCategoryDaoConfig, this);
        equipmentDao = new EquipmentDao(equipmentDaoConfig, this);
        buildingDao = new BuildingDao(buildingDaoConfig, this);
        floorDao = new FloorDao(floorDaoConfig, this);
        departmentCategoryDao = new DepartmentCategoryDao(departmentCategoryDaoConfig, this);
        departmentDao = new DepartmentDao(departmentDaoConfig, this);

        registerDao(ProcessingMode.class, processingModeDao);
        registerDao(ProcessingTimeLimit.class, processingTimeLimitDao);
        registerDao(EmergencyDegree.class, emergencyDegreeDao);
        registerDao(EquipmentCategory.class, equipmentCategoryDao);
        registerDao(Equipment.class, equipmentDao);
        registerDao(Building.class, buildingDao);
        registerDao(Floor.class, floorDao);
        registerDao(DepartmentCategory.class, departmentCategoryDao);
        registerDao(Department.class, departmentDao);
    }
    
    public void clear() {
        processingModeDaoConfig.getIdentityScope().clear();
        processingTimeLimitDaoConfig.getIdentityScope().clear();
        emergencyDegreeDaoConfig.getIdentityScope().clear();
        equipmentCategoryDaoConfig.getIdentityScope().clear();
        equipmentDaoConfig.getIdentityScope().clear();
        buildingDaoConfig.getIdentityScope().clear();
        floorDaoConfig.getIdentityScope().clear();
        departmentCategoryDaoConfig.getIdentityScope().clear();
        departmentDaoConfig.getIdentityScope().clear();
    }

    public ProcessingModeDao getProcessingModeDao() {
        return processingModeDao;
    }

    public ProcessingTimeLimitDao getProcessingTimeLimitDao() {
        return processingTimeLimitDao;
    }

    public EmergencyDegreeDao getEmergencyDegreeDao() {
        return emergencyDegreeDao;
    }

    public EquipmentCategoryDao getEquipmentCategoryDao() {
        return equipmentCategoryDao;
    }

    public EquipmentDao getEquipmentDao() {
        return equipmentDao;
    }

    public BuildingDao getBuildingDao() {
        return buildingDao;
    }

    public FloorDao getFloorDao() {
        return floorDao;
    }

    public DepartmentCategoryDao getDepartmentCategoryDao() {
        return departmentCategoryDao;
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

}
