package unicorn.com.xhsr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EQUIPMENT".
 */
public class Equipment implements java.io.Serializable {

    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private String name;
    private int orderNo;
    /** Not-null value. */
    private String categoryId;

    public Equipment() {
    }

    public Equipment(String objectId) {
        this.objectId = objectId;
    }

    public Equipment(String objectId, String name, int orderNo, String categoryId) {
        this.objectId = objectId;
        this.name = name;
        this.orderNo = orderNo;
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }

    /** Not-null value. */
    public String getCategoryId() {
        return categoryId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

}
