package unicorn.com.xhsr.greendao;

import java.util.List;
import unicorn.com.xhsr.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EQUIPMENT_CATEGORY".
 */
public class EquipmentCategory implements java.io.Serializable {

    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private String name;
    private int orderNo;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EquipmentCategoryDao myDao;

    private List<Equipment> equipmentList;

    public EquipmentCategory() {
    }

    public EquipmentCategory(String objectId) {
        this.objectId = objectId;
    }

    public EquipmentCategory(String objectId, String name, int orderNo) {
        this.objectId = objectId;
        this.name = name;
        this.orderNo = orderNo;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEquipmentCategoryDao() : null;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(int orderNo) {
        this.orderNo = orderNo;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Equipment> getEquipmentList() {
        if (equipmentList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            EquipmentDao targetDao = daoSession.getEquipmentDao();
            List<Equipment> equipmentListNew = targetDao._queryEquipmentCategory_EquipmentList(objectId);
            synchronized (this) {
                if(equipmentList == null) {
                    equipmentList = equipmentListNew;
                }
            }
        }
        return equipmentList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetEquipmentList() {
        equipmentList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
