package unicorn.com.xhsr.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FLOOR".
*/
public class FloorDao extends AbstractDao<Floor, String> {

    public static final String TABLENAME = "FLOOR";

    /**
     * Properties of entity Floor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ObjectId = new Property(0, String.class, "objectId", true, "OBJECT_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property OrderNo = new Property(2, int.class, "orderNo", false, "ORDER_NO");
        public final static Property BuildingId = new Property(3, String.class, "buildingId", false, "BUILDING_ID");
    };

    private Query<Floor> building_FloorListQuery;

    public FloorDao(DaoConfig config) {
        super(config);
    }
    
    public FloorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FLOOR\" (" + //
                "\"OBJECT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: objectId
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"ORDER_NO\" INTEGER NOT NULL ," + // 2: orderNo
                "\"BUILDING_ID\" TEXT NOT NULL );"); // 3: buildingId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FLOOR\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Floor entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getObjectId());
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getOrderNo());
        stmt.bindString(4, entity.getBuildingId());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Floor readEntity(Cursor cursor, int offset) {
        Floor entity = new Floor( //
            cursor.getString(offset + 0), // objectId
            cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // orderNo
            cursor.getString(offset + 3) // buildingId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Floor entity, int offset) {
        entity.setObjectId(cursor.getString(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setOrderNo(cursor.getInt(offset + 2));
        entity.setBuildingId(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Floor entity, long rowId) {
        return entity.getObjectId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Floor entity) {
        if(entity != null) {
            return entity.getObjectId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "floorList" to-many relationship of Building. */
    public List<Floor> _queryBuilding_FloorList(String buildingId) {
        synchronized (this) {
            if (building_FloorListQuery == null) {
                QueryBuilder<Floor> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BuildingId.eq(null));
                queryBuilder.orderRaw("T.'ORDER_NO' ASC");
                building_FloorListQuery = queryBuilder.build();
            }
        }
        Query<Floor> query = building_FloorListQuery.forCurrentThread();
        query.setParameter(0, buildingId);
        return query.list();
    }

}
